### ISSUE TITLE
[FEATURE] 공연 디비 제거

### ISSUE THREAD

**Issue by Cho-D-YoungRae** [CurtainCall-App/CurtainCall-Server#146]
## Todo

- [ ]  kopis api 사용
- [ ] api 호출 많아질테니 `WebClient` 사용
- [ ] redis 캐싱 검토
