### ISSUE TITLE
[FEATURE] 분실물 기획 변경 반영

### ISSUE THREAD

**Issue by Cho-D-YoungRae** [CurtainCall-App/CurtainCall-Server#154]
## Todo

- [x] 분실물 카테고리 제거
- [x] 기간 조회 기능
- [x] 조회 기능 전체적으로 확인
